# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-04-21 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaindustria',
            name='descripcion_industria',
        ),
    ]
